export const EXAMPLESBOOTSTRAP = [
    {
        id: 0,
        name: "PROJECT INFO",
        software: "BOOTSTRAP CSS HTML 1",
        description: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. ",
        image: "/assets/images/project-2-image.png",
        github: "https://github.com/Alicia-M-M",
        figma: "https://www.figma.com/",
        linkedIn: "https://www.linkedin.com/",
    },
    {
        id: 1,
        name: "PROJECT INFO",
        software: "BOOTSTRAP CSS HTML 2",
        description: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. ",
        image: "/assets/images/project-2-image.png",
        github: "https://github.com/Alicia-M-M",
        figma: "https://www.figma.com/",
        linkedIn: "https://www.linkedin.com/",
    },
    {
        id: 2,
        name: "PROJECT INFO",
        software: "BOOTSTRAP CSS HTML 3",
        description: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. ",
        image: "/assets/images/project-2-image.png",
        github: "https://github.com/Alicia-M-M",
        figma: "https://www.figma.com/",
        linkedIn: "https://www.linkedin.com/",
    },
]