export const EXAMPLES_LOADING = 'EXAMPLES_LOADING';
export const EXAMPLES_FAILED = 'EXAMPLES_FAILED';
export const ADD_EXAMPLES = 'ADD_EXAMPLES';

// ABOUTINFO

export const ABOUTINFO_LOADING = 'ABOUTINFO_LOADING';
export const ABOUTINFO_FAILED = 'ABOUTINFO_FAILED';
export const ADD_ABOUTINFO = 'ADD_ABOUTINFO';

// HERO

export const HERO_LOADING = 'HERO_LOADING';
export const HERO_FAILED = 'HERO_FAILED';
export const ADD_HERO = 'ADD_HERO';

// PAGELINKS

export const PAGELINKS_LOADING = 'PAGELINKS_LOADING';
export const PAGELINKS_FAILED = 'PAGELINKS_FAILED';
export const ADD_PAGELINKS = 'ADD_PAGELINKS';

// EXAMPLESBACKEND

export const EXAMPLESBACKEND_LOADING = 'EXAMPLESBACKEND_LOADING';
export const EXAMPLESBACKEND_FAILED = 'EXAMPLESBACKEND_FAILED';
export const ADD_EXAMPLESBACKEND = 'ADD_EXAMPLESBACKEND';

// EXAMPLESREACT

export const EXAMPLESREACT_LOADING = 'EXAMPLESREACT_LOADING';
export const EXAMPLESREACT_FAILED = 'EXAMPLESREACT_FAILED';
export const ADD_EXAMPLESREACT = 'ADD_EXAMPLESREACT';

// EXAMPLESBOOTSTRAP

export const EXAMPLESBOOTSTRAP_LOADING = 'EXAMPLESBOOTSTRAP_LOADING';
export const EXAMPLESBOOTSTRAP_FAILED = 'EXAMPLESBOOTSTRAP_FAILED';
export const ADD_EXAMPLESBOOTSTRAP = 'ADD_EXAMPLESBOOTSTRAP';

// EXAMPLESMISC

export const EXAMPLESMISC_LOADING = 'EXAMPLESMISC_LOADING';
export const EXAMPLESMISC_FAILED = 'EXAMPLESMISC_FAILED';
export const ADD_EXAMPLESMISC = 'ADD_EXAMPLESMISC';