export const EXAMPLES_LOADING = 'EXAMPLES_LOADING';
export const EXAMPLES_FAILED = 'EXAMPLES_FAILED';
export const ADD_EXAMPLES = 'ADD_EXAMPLES';

// ABOUTINFO

export const ABOUTINFO_LOADING = 'ABOUTINFO_LOADING';
export const ABOUTINFO_FAILED = 'ABOUTINFO_FAILED';
export const ADD_ABOUTINFO = 'ADD_ABOUTINFO';

// HERO

export const HERO_LOADING = 'HERO_LOADING';
export const HERO_FAILED = 'HERO_FAILED';
export const ADD_HERO = 'ADD_HERO';

// PAGELINKS

export const PAGELINKS_LOADING = 'PAGELINKS_LOADING';
export const PAGELINKS_FAILED = 'PAGELINKS_FAILED';
export const ADD_PAGELINKS = 'ADD_PAGELINKS';